export const bundles = [
  {
    id: "b1",
    title: "React  CSS3  Firebase",
    bg: "315deg, #20bf55 0%, #01baef 74%",
    contents: ["reactjs", "css", "html", "firebase", "javascript", "nodejs"],
  },
  {
    id: "b2",
    title: "NextJS  CSS3  MongoDB",
    bg: "315deg, #ee8c68 0%, #eb6b9d 74%",
    contents: [
      "reactjs",
      "nextjs",
      "mongodb",
      "css",
      "html",
      "javascript",
      "nodejs",
    ],
  },
  {
    id: "b3",
    title: "NextJS  CSS3  Firebase",
    bg: "315deg, #ee9617 0%, #fe5858 74%",
    contents: [
      "reactjs",
      "nextjs",
      "firebase",
      "css",
      "html",
      "javascript",
      "nodejs",
    ],
  },
  {
    id: "b4",
    title: "NextJS  CSS3  PostgreSQL",
    bg: "315deg, #42378f 0%, #f53844 74%",
    contents: [
      "reactjs",
      "nextjs",
      "postgresql",
      "sql",
      "css",
      "html",
      "javascript",
      "nodejs",
    ],
  },
  {
    id: "b5",
    title: "ExpressJS  REST  Firebase",
    bg: "315deg, #2a2a72 0%, #009ffd 74%",
    contents: ["firebase", "javascript", "nodejs", "express"],
  },
  {
    id: "b6",
    title: "ExpressJS  REST  MongoDB",
    bg: "315deg, #3bb78f 0%, #0bab64 74%",
    contents: ["javascript", "nodejs", "mongodb", "express"],
  },
];
export const techs = [
  {
    id: "t1",
    title: "HTML5 ",
    bg: "315deg, #06bcfb 0%, #4884ee 74%",
    contents: ["html"],
  },
  {
    id: "t2",
    title: "CSS3",
    bg: "315deg, #f7b42c 0%, #fc575e 74%",
    contents: ["css"],
  },
  {
    id: "t3",
    title: "Javascript",
    bg: "215deg, #29539b 50%, #1e3b70 74%",
    contents: ["javascript"],
  },
  {
    id: "t4",
    title: "React",
    bg: "315deg, #ff0c44 0%, #b91372 74%",
    contents: ["reactjs"],
    dependencies: ["javascript", "nodejs"],
  },
  {
    id: "t5",
    title: "NextJS",
    bg: "315deg, #0beef9 0%, #48a9fe 74%",
    contents: ["nextjs"],
    dependencies: ["javascript", "nodejs", "reactjs"],
  },
  {
    id: "t6",
    title: "Express",
    bg: "315deg, #726cf8 0%, #e975a8 74%",
    contents: ["express"],
    dependencies: ["javascript", "nodejs"],
  },
  {
    id: "t7",
    title: "Firebase",
    bg: "315deg,#ffcf5f,#e99b00",
    contents: ["firebase"],
    dependencies: ["javascript", "nodejs"],
  },
  {
    id: "t8",
    title: "MongoDB",
    bg: "315deg, #3bb78f 0%, #0bab64 74%",
    contents: ["mongodb"],
    dependencies: ["javascript", "nodejs"],
  },
  {
    id: "t9",
    title: "SQL",
    bg: "315deg, #6b0f1a 0%, #b91372 74%",
    contents: ["sql"],
    dependencies: ["javascript", "nodejs"],
  },
  {
    id: "t10",
    title: "PostgreSQL",
    bg: "326deg, #a4508b 0%, #5f0a87 74%",
    contents: ["postgresql"],
    dependencies: ["javascript", "nodejs", "sql"],
  },
];

export const countries =
  '[{"c":"+880","n":"Bangladesh"},{"c":"+32","n":"Belgium"},{"c":"+226","n":"Burkina Faso"},{"c":"+359","n":"Bulgaria"},{"c":"+387","n":"Bosnia and Herzegovina"},{"c":"+1-246","n":"Barbados"},{"c":"+681","n":"Wallis and Futuna"},{"c":"+590","n":"Saint Barthelemy"},{"c":"+1-441","n":"Bermuda"},{"c":"+673","n":"Brunei"},{"c":"+591","n":"Bolivia"},{"c":"+973","n":"Bahrain"},{"c":"+257","n":"Burundi"},{"c":"+229","n":"Benin"},{"c":"+975","n":"Bhutan"},{"c":"+1-876","n":"Jamaica"},{"c":"+","n":"Bouvet Island"},{"c":"+267","n":"Botswana"},{"c":"+685","n":"Samoa"},{"c":"+599","n":"Bonaire, Saint Eustatius and Saba "},{"c":"+55","n":"Brazil"},{"c":"+1-242","n":"Bahamas"},{"c":"+44-1534","n":"Jersey"},{"c":"+375","n":"Belarus"},{"c":"+501","n":"Belize"},{"c":"+7","n":"Russia"},{"c":"+250","n":"Rwanda"},{"c":"+381","n":"Serbia"},{"c":"+670","n":"East Timor"},{"c":"+262","n":"Reunion"},{"c":"+993","n":"Turkmenistan"},{"c":"+992","n":"Tajikistan"},{"c":"+40","n":"Romania"},{"c":"+690","n":"Tokelau"},{"c":"+245","n":"Guinea-Bissau"},{"c":"+1-671","n":"Guam"},{"c":"+502","n":"Guatemala"},{"c":"+30","n":"Greece"},{"c":"+240","n":"Equatorial Guinea"},{"c":"+590","n":"Guadeloupe"},{"c":"+81","n":"Japan"},{"c":"+592","n":"Guyana"},{"c":"+44-1481","n":"Guernsey"},{"c":"+594","n":"French Guiana"},{"c":"+995","n":"Georgia"},{"c":"+1-473","n":"Grenada"},{"c":"+44","n":"United Kingdom"},{"c":"+241","n":"Gabon"},{"c":"+503","n":"El Salvador"},{"c":"+224","n":"Guinea"},{"c":"+220","n":"Gambia"},{"c":"+299","n":"Greenland"},{"c":"+350","n":"Gibraltar"},{"c":"+233","n":"Ghana"},{"c":"+968","n":"Oman"},{"c":"+216","n":"Tunisia"},{"c":"+962","n":"Jordan"},{"c":"+385","n":"Croatia"},{"c":"+509","n":"Haiti"},{"c":"+36","n":"Hungary"},{"c":"+852","n":"Hong Kong"},{"c":"+504","n":"Honduras"},{"c":"+ ","n":"Heard Island and McDonald Islands"},{"c":"+58","n":"Venezuela"},{"c":"+1-787 and 1-939","n":"Puerto Rico"},{"c":"+970","n":"Palestinian Territory"},{"c":"+680","n":"Palau"},{"c":"+351","n":"Portugal"},{"c":"+47","n":"Svalbard and Jan Mayen"},{"c":"+595","n":"Paraguay"},{"c":"+964","n":"Iraq"},{"c":"+507","n":"Panama"},{"c":"+689","n":"French Polynesia"},{"c":"+675","n":"Papua New Guinea"},{"c":"+51","n":"Peru"},{"c":"+92","n":"Pakistan"},{"c":"+63","n":"Philippines"},{"c":"+870","n":"Pitcairn"},{"c":"+48","n":"Poland"},{"c":"+508","n":"Saint Pierre and Miquelon"},{"c":"+260","n":"Zambia"},{"c":"+212","n":"Western Sahara"},{"c":"+372","n":"Estonia"},{"c":"+20","n":"Egypt"},{"c":"+27","n":"South Africa"},{"c":"+593","n":"Ecuador"},{"c":"+39","n":"Italy"},{"c":"+84","n":"Vietnam"},{"c":"+677","n":"Solomon Islands"},{"c":"+251","n":"Ethiopia"},{"c":"+252","n":"Somalia"},{"c":"+263","n":"Zimbabwe"},{"c":"+966","n":"Saudi Arabia"},{"c":"+34","n":"Spain"},{"c":"+291","n":"Eritrea"},{"c":"+382","n":"Montenegro"},{"c":"+373","n":"Moldova"},{"c":"+261","n":"Madagascar"},{"c":"+590","n":"Saint Martin"},{"c":"+212","n":"Morocco"},{"c":"+377","n":"Monaco"},{"c":"+998","n":"Uzbekistan"},{"c":"+95","n":"Myanmar"},{"c":"+223","n":"Mali"},{"c":"+853","n":"Macao"},{"c":"+976","n":"Mongolia"},{"c":"+692","n":"Marshall Islands"},{"c":"+389","n":"Macedonia"},{"c":"+230","n":"Mauritius"},{"c":"+356","n":"Malta"},{"c":"+265","n":"Malawi"},{"c":"+960","n":"Maldives"},{"c":"+596","n":"Martinique"},{"c":"+1-670","n":"Northern Mariana Islands"},{"c":"+1-664","n":"Montserrat"},{"c":"+222","n":"Mauritania"},{"c":"+44-1624","n":"Isle of Man"},{"c":"+256","n":"Uganda"},{"c":"+255","n":"Tanzania"},{"c":"+60","n":"Malaysia"},{"c":"+52","n":"Mexico"},{"c":"+972","n":"Israel"},{"c":"+33","n":"France"},{"c":"+246","n":"British Indian Ocean Territory"},{"c":"+290","n":"Saint Helena"},{"c":"+358","n":"Finland"},{"c":"+679","n":"Fiji"},{"c":"+500","n":"Falkland Islands"},{"c":"+691","n":"Micronesia"},{"c":"+298","n":"Faroe Islands"},{"c":"+505","n":"Nicaragua"},{"c":"+31","n":"Netherlands"},{"c":"+47","n":"Norway"},{"c":"+264","n":"Namibia"},{"c":"+678","n":"Vanuatu"},{"c":"+687","n":"New Caledonia"},{"c":"+227","n":"Niger"},{"c":"+672","n":"Norfolk Island"},{"c":"+234","n":"Nigeria"},{"c":"+64","n":"New Zealand"},{"c":"+977","n":"Nepal"},{"c":"+674","n":"Nauru"},{"c":"+683","n":"Niue"},{"c":"+682","n":"Cook Islands"},{"c":"+","n":"Kosovo"},{"c":"+225","n":"Ivory Coast"},{"c":"+41","n":"Switzerland"},{"c":"+57","n":"Colombia"},{"c":"+86","n":"China"},{"c":"+237","n":"Cameroon"},{"c":"+56","n":"Chile"},{"c":"+61","n":"Cocos Islands"},{"c":"+1","n":"Canada"},{"c":"+242","n":"Republic of the Congo"},{"c":"+236","n":"Central African Republic"},{"c":"+243","n":"Democratic Republic of the Congo"},{"c":"+420","n":"Czech Republic"},{"c":"+357","n":"Cyprus"},{"c":"+61","n":"Christmas Island"},{"c":"+506","n":"Costa Rica"},{"c":"+599","n":"Curacao"},{"c":"+238","n":"Cape Verde"},{"c":"+53","n":"Cuba"},{"c":"+268","n":"Swaziland"},{"c":"+963","n":"Syria"},{"c":"+599","n":"Sint Maarten"},{"c":"+996","n":"Kyrgyzstan"},{"c":"+254","n":"Kenya"},{"c":"+211","n":"South Sudan"},{"c":"+597","n":"Suriname"},{"c":"+686","n":"Kiribati"},{"c":"+855","n":"Cambodia"},{"c":"+1-869","n":"Saint Kitts and Nevis"},{"c":"+269","n":"Comoros"},{"c":"+239","n":"Sao Tome and Principe"},{"c":"+421","n":"Slovakia"},{"c":"+82","n":"South Korea"},{"c":"+386","n":"Slovenia"},{"c":"+850","n":"North Korea"},{"c":"+965","n":"Kuwait"},{"c":"+221","n":"Senegal"},{"c":"+378","n":"San Marino"},{"c":"+232","n":"Sierra Leone"},{"c":"+248","n":"Seychelles"},{"c":"+7","n":"Kazakhstan"},{"c":"+1-345","n":"Cayman Islands"},{"c":"+65","n":"Singapore"},{"c":"+46","n":"Sweden"},{"c":"+249","n":"Sudan"},{"c":"+1-809 and 1-829","n":"Dominican Republic"},{"c":"+1-767","n":"Dominica"},{"c":"+253","n":"Djibouti"},{"c":"+45","n":"Denmark"},{"c":"+1-284","n":"British Virgin Islands"},{"c":"+49","n":"Germany"},{"c":"+967","n":"Yemen"},{"c":"+213","n":"Algeria"},{"c":"+1","n":"United States"},{"c":"+598","n":"Uruguay"},{"c":"+262","n":"Mayotte"},{"c":"+1","n":"United States Minor Outlying Islands"},{"c":"+961","n":"Lebanon"},{"c":"+1-758","n":"Saint Lucia"},{"c":"+856","n":"Laos"},{"c":"+688","n":"Tuvalu"},{"c":"+886","n":"Taiwan"},{"c":"+1-868","n":"Trinidad and Tobago"},{"c":"+90","n":"Turkey"},{"c":"+94","n":"Sri Lanka"},{"c":"+423","n":"Liechtenstein"},{"c":"+371","n":"Latvia"},{"c":"+676","n":"Tonga"},{"c":"+370","n":"Lithuania"},{"c":"+352","n":"Luxembourg"},{"c":"+231","n":"Liberia"},{"c":"+266","n":"Lesotho"},{"c":"+66","n":"Thailand"},{"c":"+","n":"French Southern Territories"},{"c":"+228","n":"Togo"},{"c":"+235","n":"Chad"},{"c":"+1-649","n":"Turks and Caicos Islands"},{"c":"+218","n":"Libya"},{"c":"+379","n":"Vatican"},{"c":"+1-784","n":"Saint Vincent and the Grenadines"},{"c":"+971","n":"United Arab Emirates"},{"c":"+376","n":"Andorra"},{"c":"+1-268","n":"Antigua and Barbuda"},{"c":"+93","n":"Afghanistan"},{"c":"+1-264","n":"Anguilla"},{"c":"+1-340","n":"U.S. Virgin Islands"},{"c":"+354","n":"Iceland"},{"c":"+98","n":"Iran"},{"c":"+374","n":"Armenia"},{"c":"+355","n":"Albania"},{"c":"+244","n":"Angola"},{"c":"+","n":"Antarctica"},{"c":"+1-684","n":"American Samoa"},{"c":"+54","n":"Argentina"},{"c":"+61","n":"Australia"},{"c":"+43","n":"Austria"},{"c":"+297","n":"Aruba"},{"c":"+91","n":"India"},{"c":"+358-18","n":"Aland Islands"},{"c":"+994","n":"Azerbaijan"},{"c":"+353","n":"Ireland"},{"c":"+62","n":"Indonesia"},{"c":"+380","n":"Ukraine"},{"c":"+974","n":"Qatar"},{"c":"+258","n":"Mozambique"}]';
