import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import Page from "../components/Page";

/* HomePage file   - All js/ts files in /pages are pages or the app*/

export default function Home() {
  const bundles = [
    { id: 1, title: "React + CSS + Firebase" },
    { id: 2, title: "NextJS + CSS + MongoDB" },
    { id: 3, title: "NextJS + CSS + Firebase" },
  ];

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page>
        <div className="bundles">
          <div className="head flex">
            <h4>Bundles</h4>
            <p>Learn a set of technologies..</p>
          </div>
          <div className="content flex">
            {bundles.map(function (item, index) {
              return (
                <div
                  key={item.id}
                  style={{ border: "2px solid #000" }}
                  className="item"
                >
                  <h2>{item.title}</h2>
                  <Button>Select</Button>
                </div>
              );
            })}
          </div>
        </div>
        <div className="techs"></div>
      </Page>
    </div>
  );
}
